version: '3.8'

services:
  mds-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mds-task-manager-app
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html/src 
    networks:
      - app-network
    depends_on:
      - mds-db

  mds-db:
    image: mysql:8.0
    container_name: mds-task-manager-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:  
